# Generated by Django 2.2.5 on 2019-09-22 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sproduct', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stuck',
            new_name='stock',
        ),
    ]
