# Generated by Django 2.2.5 on 2019-09-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='', max_length=8, verbose_name='등급'),
            preserve_default=False,
        ),
    ]
